### ISSUE TITLE
OAuth FAIL: Now I cannot authorize the app

### ISSUE THREAD

**Issue by al-the-x** [gwoo/phpneeds#1]
When I first landed on the site, I clicked the upvote link on a suggestion (by accident), which took me to an OAuth page for Twitter. I backed up, neither pressing "confirm" or "deny" (or whatever the page said). When I click on the upvote link anymore, I'm no longer prompted to authorize the app. I've checked my Twitter > Settings > Applications page, and the app isn't listed. Thoughts?

**Comment by al-the-x** [comment]
In `controllers/IdeasController.php`, line 34:

```
        if (!$this->request->user) {
            return $this->redirect('Login::index');
        }
```

I suspect that `$this->request->user` is set because I started the OAuth dance but didn't complete it. I could be wrong, though, since I'm not familiar with how `li3_oauth` works. Just a thought.

**Comment by gwoo** [comment]
interesting. looking into the issue. among others.
